#version 450
#extension GL_EXT_nonuniform_qualifier : enable
#include "common.glsl"

layout(local_size_x = 256) in;

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= pc.particleCount) return;
    if (readVec4(pc.invMassIdx, i).x != 0.0) return;

    vec4 t = readVec4(pc.pinnedTargetIdx, i);
    writeVec4(pc.posIdx,   i, t);
    writeVec4(pc.predPIdx, i, t);
    writeVec4(pc.velIdx,   i, vec4(0.0, 0.0, 0.0, 0.0));
}
