#version 450
#extension GL_EXT_nonuniform_qualifier : enable
#include "mpm_common.glsl"

layout(local_size_x = 256) in;

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= pc.particleCount) return;

    vec3 pos = readVec4(pc.posIdx, i).xyz;
    uint cid = cellIdFromPos(pos);
    uint slot = atomicAdd(buffers[pc.cellOffsetIdx].data[cid], 1u);
    buffers[pc.sortedIdxIdx].data[slot] = i;
}
